import { chromium } from '@playwright/test';
import { execFileSync, spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const front = process.cwd(), root = path.resolve(front, '..');
const work = mkdtempSync(path.join(tmpdir(), 'gecc-review-'));
const env = {...process.env, GECC_DEV:'1', GECC_SQLITE_PATH:path.join(work,'review.sqlite3'),GECC_DEMO_PASSWORD:'ScreenReview2026!',GECC_SANDBOX_TEST_EMAILS:'customer@testing-gecc.com,gecc@testing-gecc.com'};
// An isolated SQLite development database contains synthetic records only.
for(const key of ['PGHOST','PGDATABASE','PGUSER','PGPORT','PGPASSWORD']) delete env[key];
for(const command of ['migrate','bootstrap_dev']) execFileSync('python',[path.join(root,'backend/manage.py'),command],{env,stdio:'pipe'});
const backend=spawn('python',[path.join(root,'backend/manage.py'),'runserver','127.0.0.1:8000','--noreload'],{env,stdio:'pipe'});
const frontend=spawn(process.execPath,[path.join(front,'node_modules/vite/bin/vite.js'),'--host','127.0.0.1','--port','5173','--strictPort'],{cwd:front,env,stdio:'pipe'});
const errors=[];for(const server of [backend,frontend])server.stderr.on('data',d=>errors.push(d.toString()));
let browser,page;
try{
 for(let i=0;i<100;i++){try{const r=await fetch('http://127.0.0.1:5173/api/csrf/');if(r.ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,...(process.env.GECC_BROWSER_EXECUTABLE?{executablePath:process.env.GECC_BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']}: {})});
 page=await browser.newPage({viewport:{width:1440,height:1000}});const browserErrors=[];page.on('pageerror',e=>browserErrors.push(e.message));
 const shots=process.env.GECC_SCREENSHOTS || path.join(work,'screens');mkdirSync(shots,{recursive:true});
 async function shot(name){await page.screenshot({path:path.join(shots,`${name}.png`),fullPage:true});}
 async function signIn(username){await page.getByRole('heading',{name:'Sign in',exact:true}).waitFor();await page.goto('http://127.0.0.1:5173');await page.getByLabel('Username',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill(env.GECC_DEMO_PASSWORD);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Customers & projects'}).waitFor();}
 await page.goto('http://127.0.0.1:5173');await page.getByRole('heading',{name:'Sign in',exact:true}).waitFor();await shot('01-login');
 await signIn('sales');await page.getByRole('button',{name:'Add customer',exact:true}).click();await page.getByLabel('Legal name').fill('Screen Review Customer');await page.getByLabel('Billing address',{exact:true}).fill('20 Example Lane, Germantown, MD 20876');await page.getByLabel('Email',{exact:true}).fill('review@example.invalid');await page.getByLabel('Phone',{exact:true}).fill('301-555-0100');await page.getByRole('button',{name:'Save customer',exact:true}).click();await page.getByRole('heading',{name:'New customer'}).waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Create project',exact:true}).click();await page.locator('select[name="customer"]').selectOption({label:'Screen Review Customer'});await page.getByLabel('Installation address',{exact:true}).fill('22 Example Lane');await page.locator('select[name="reviewer"]').selectOption({label:'manager'});await page.getByRole('button',{name:'Create draft'}).click();await page.getByRole('heading',{name:'Master Sales Record • Version 1.0'}).waitFor();
 await page.getByLabel('Scope of work',{exact:true}).fill('Install a replacement heat pump and thermostat. Remove the existing equipment.');await page.getByLabel('Base price ($)',{exact:true}).fill('12000.00');await page.getByLabel('Discount ($)',{exact:true}).fill('500.00');await page.getByLabel('Tax ($)',{exact:true}).fill('690.00');await page.getByLabel('Total price ($)',{exact:true}).fill('12190.00');await page.getByLabel('Payment terms',{exact:true}).fill('50% deposit when legally eligible; remaining 50% on completion.');await page.getByRole('button',{name:'Add equipment item'}).click();await page.getByLabel('Description',{exact:true}).fill('Heat pump');await shot('02-draft');
 await page.getByRole('button',{name:'Save & submit',exact:true}).click();await page.getByText('Version 1.0 • SUBMITTED',{exact:false}).waitFor();assert.equal(await page.getByLabel('Scope of work',{exact:true}).isDisabled(),true);await shot('03-submitted');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('manager');await page.locator('button.project').first().click();await page.getByRole('button',{name:'Approve version',exact:true}).click();await page.getByText('The approved record is locked.',{exact:false}).waitFor();await shot('04-approved');
 async function prepare(button,kind){await page.getByRole('button',{name:button,exact:true}).click();const row=page.locator('.document-row').filter({has:page.getByText(kind,{exact:true})});await row.waitFor();const event=page.waitForEvent('download');await row.getByRole('link',{name:'Download PDF'}).click();const download=await event;await download.saveAs(path.join(shots,download.suggestedFilename()));}
 await prepare('Prepare contract','CONTRACT');await prepare('Prepare invoice','INVOICE');await prepare('Prepare completion certificate','COMPLETION NON FINANCED');await shot('07-documents');
 await page.getByLabel('Customer signer full name',{exact:true}).fill('Synthetic Authorized Customer');await page.getByLabel('Customer signer email',{exact:true}).fill('review@example.invalid');await page.getByLabel('GECC signer',{exact:true}).selectOption({label:'Demo Manager · SALES MANAGER'});await page.getByLabel('Signer identity and authority review',{exact:true}).fill('Synthetic test identity and authority review.');await page.getByRole('button',{name:'Save signing review',exact:true}).click();await page.locator('.signing-review > summary').getByText('MSR 1.0 · COMMERCIAL · PREPARED',{exact:true}).waitFor();await page.locator('.signing-review > summary').click();assert.equal(await page.getByRole('button',{name:'Send for signatures',exact:true}).isDisabled(),true);const routing=await page.locator('.signing-review ol li').allTextContents();assert.match(routing[0],/Synthetic Authorized Customer/);assert.match(routing[1],/Demo Manager/);assert.equal(await page.getByText("Failed to execute 'json' on 'Response': Unexpected end of JSON input",{exact:true}).count(),0);await shot('09-signing-review');await page.getByRole('button',{name:'Prepare sandbox package',exact:true}).click();await page.getByRole('link',{name:'Download sandbox contract',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Authorize unsent sandbox draft',exact:true}).count(),0);await shot('12-sandbox-package');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('comptroller');await page.locator('button.project').first().click();await page.getByText('Project verification evidence',{exact:true}).click();await page.getByLabel('Evidence reference',{exact:true}).fill('Synthetic cancellation notice fixture');await page.getByLabel('Verification note',{exact:true}).fill('Screen test only; no actual legal deadline has been verified.');await page.getByLabel('Exact cancellation deadline with UTC offset',{exact:true}).fill('2026-10-20T23:59:00-04:00');await page.getByLabel('I reviewed applicable cancellation rights, notice delivery and the exact deadline against the evidence reference.',{exact:true}).check();await page.getByRole('button',{name:'Save verification evidence',exact:true}).click();await page.getByText('Recorded verification',{exact:false}).waitFor();await page.locator('.signing-review > summary').click();await page.getByRole('button',{name:'Prepare release review package',exact:true}).click();await page.getByRole('link',{name:'Download release contract',exact:true}).waitFor();await shot('13-verification-release');
 // Seed an explicitly synthetic provider observation; this screen test never calls Docusign.
 execFileSync('python',[path.join(root,'backend/manage.py'),'shell','-c',`
from core.models import SandboxPackage, SandboxAttempt, SandboxObservation, DocusignChallenge, User
from core.documents import canonical_hash
from django.utils import timezone
from datetime import timedelta
p=SandboxPackage.objects.get()
u=User.objects.get(username='comptroller')
c=DocusignChallenge.objects.create(actor=u,state_digest='a'*64,session_digest='b'*64,configuration_digest='c'*64,expires_at=timezone.now()+timedelta(minutes=10))
a=SandboxAttempt.objects.create(package=p,actor=u,challenge=c,state='RECONCILIATION_REQUIRED',account_id='22222222-2222-4222-8222-222222222222',envelope_id='55555555-5555-4555-8555-555555555555')
e={'outcome':'CHANGED','observed_at':timezone.now().isoformat(),'metadata_matched':False,'provider_status':'created','blockers':['Synthetic screen fixture: provider metadata changed.'],'send_available':False,'provider_pdf_bytes_verified':False}
SandboxObservation.objects.create(attempt=a,challenge=c,created_by=u,evidence=e,digest=canonical_hash(e))
`],{env,stdio:'pipe'});
 await page.getByRole('button',{name:'Refresh sandbox draft status',exact:true}).click();await page.getByText('Synthetic screen fixture: provider metadata changed.',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Check existing sandbox draft',exact:true}).isDisabled(),true);await page.getByLabel('I authorize a read-only check of this existing sandbox draft.',{exact:true}).check();assert.equal(await page.getByRole('button',{name:'Check existing sandbox draft',exact:true}).isDisabled(),false);assert.equal(await page.getByRole('button',{name:'Send for signatures',exact:true}).isDisabled(),true);await shot('15-sandbox-reconciliation');

 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('manager');await page.locator('button.project').first().click();await page.locator('.signing-review > summary').click();await page.getByLabel('Release review note',{exact:true}).fill('Synthetic independent document/evidence review.');await page.getByLabel('I reviewed these exact documents, recipient identities, routing and referenced verification evidence.',{exact:true}).check();await page.getByRole('button',{name:'Record release decision',exact:true}).click();await page.getByText('Release review:',{exact:false}).filter({has:page.getByText('APPROVED',{exact:true})}).waitFor();assert.equal(await page.getByRole('button',{name:'Send for signatures',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Check existing sandbox draft',exact:true}).count(),0);await shot('14-independent-release-approval');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('comptroller');await page.locator('button.project').first().click();await page.locator('.signing-review > summary').click();await page.getByText('Sandbox signing test',{exact:true}).click();await page.getByLabel('Customer test email',{exact:true}).fill('customer@testing-gecc.com');await page.getByLabel('GECC test email',{exact:true}).fill('gecc@testing-gecc.com');await page.getByLabel('Signing-test preparation note',{exact:true}).fill('Synthetic browser test only; no actual agreement or work verified.');await page.getByLabel('This is a fictional project used only to test the software.',{exact:true}).check();await page.getByLabel('I control both test email addresses and authorize their use for this test.',{exact:true}).check();await page.getByRole('button',{name:'Prepare signing-test package',exact:true}).click();await page.getByRole('link',{name:'Download signing-test contract',exact:true}).waitFor();await shot('16-signing-test-package');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('manager');await page.locator('button.project').first().click();await page.locator('.signing-review > summary').click();await page.getByText('Sandbox signing test',{exact:true}).click();await page.getByLabel('Signing-test review note',{exact:true}).fill('Synthetic independent signing-test package review.');await page.getByLabel('I reviewed these exact signing-test PDFs, controlled email addresses, names and routing.',{exact:true}).check();await page.getByRole('button',{name:'Record signing-test decision',exact:true}).click();await page.getByText('Signing-test review:',{exact:false}).filter({has:page.getByText('APPROVED',{exact:true})}).waitFor();assert.equal(await page.getByRole('button',{name:'Authorize sandbox signing test',exact:true}).count(),0);await shot('17-signing-test-approval');



 await page.getByLabel('Review note / revision reason').fill('Revise thermostat model');await page.getByRole('button',{name:'Create revision',exact:true}).click();await page.getByRole('heading',{name:'Master Sales Record • Version 2.0'}).waitFor();await page.getByText('Approved: Version 1.0',{exact:true}).waitFor();await shot('05-revision');
 await page.setViewportSize({width:390,height:844});await shot('06-mobile');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile page must not scroll horizontally');
 await page.setViewportSize({width:1440,height:1000});await page.getByLabel('Financing',{exact:true}).selectOption('FINANCED');await page.getByRole('button',{name:'Save & submit',exact:true}).click();await page.getByText('Version 2.0 • SUBMITTED',{exact:false}).waitFor();await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('comptroller');await page.getByText('Docusign sandbox setup',{exact:true}).click();await page.getByText('Server configuration needed',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Verify sandbox account',exact:true}).isDisabled(),true);await shot('11-docusign-setup');await page.getByText('Docusign sandbox setup',{exact:true}).click();await page.locator('button.project').first().click();await page.getByRole('button',{name:'Approve version',exact:true}).click();await page.getByText('Approved: Version 2.0',{exact:true}).waitFor();await prepare('Prepare completion certificate','COMPLETION FINANCED');await shot('08-financed-documents');assert.equal(await page.locator('.document-row').count(),4);await page.locator('.signing-review > summary').getByText('MSR 1.0 · COMMERCIAL · SUPERSEDED',{exact:true}).waitFor();await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Signing review mobile layout must fit');await shot('10-signing-mobile');

 // Account management uses an isolated fictional account and never emails anyone.
 await page.getByRole('button',{name:'User management',exact:true}).click();await page.getByRole('heading',{name:'User management',exact:true}).waitFor();
 await page.getByRole('button',{name:'Edit user comptroller',exact:true}).click();assert.equal(await page.getByLabel('User role',{exact:true}).isDisabled(),true);assert.equal(await page.getByLabel('Account active — can sign in',{exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Cancel user changes',exact:true}).click();
 await page.getByRole('button',{name:'Add user',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill('synthetictech');await page.getByLabel('User first name',{exact:true}).fill('Synthetic');await page.getByLabel('User last name',{exact:true}).fill('Technician');await page.getByLabel('User email',{exact:true}).fill('technician@example.invalid');await page.getByLabel('User initials',{exact:true}).fill('ST');await page.getByLabel('Local password',{exact:true}).fill('SyntheticAccount2026!');await page.getByLabel('Account change note',{exact:true}).fill('Fictional account creation for browser testing.');await page.getByRole('button',{name:'Create user',exact:true}).click();await page.getByRole('status').filter({hasText:'User created.'}).waitFor();
 await page.getByRole('button',{name:'Edit user synthetictech',exact:true}).click();await page.getByLabel('User role',{exact:true}).selectOption('TECHNICIAN');await page.getByLabel('Account active — can sign in',{exact:true}).uncheck();await page.getByLabel('Account change note',{exact:true}).fill('Synthetic role change and deactivation test.');await page.getByRole('button',{name:'Save user changes',exact:true}).click();await page.getByRole('status').filter({hasText:'User changes saved.'}).waitFor();await shot('18-user-management');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'User management mobile layout must fit');await shot('19-users-mobile');await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill('synthetictech');await page.getByLabel('Password',{exact:true}).fill('SyntheticAccount2026!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('alert').filter({hasText:'Invalid credentials.'}).waitFor();
 await signIn('comptroller');await page.getByRole('button',{name:'User management',exact:true}).click();await page.getByRole('button',{name:'Edit user synthetictech',exact:true}).click();await page.getByLabel('Account active — can sign in',{exact:true}).check();await page.getByLabel('New local password (optional)',{exact:true}).fill('ReplacementTest2026!');await page.getByLabel('Account change note',{exact:true}).fill('Synthetic reactivation and local password reset test.');await page.getByRole('button',{name:'Save user changes',exact:true}).click();await page.getByRole('status').filter({hasText:'User changes saved.'}).waitFor();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill('synthetictech');await page.getByLabel('Password',{exact:true}).fill('ReplacementTest2026!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Customers & projects'}).waitFor();assert.equal(await page.getByRole('button',{name:'User management',exact:true}).count(),0);assert.equal(await page.locator('button.project').count(),0);assert.equal(await page.getByRole('button',{name:'Manage customers',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Audit history',exact:true}).count(),0);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('manager');assert.equal(await page.getByRole('button',{name:'User management',exact:true}).count(),0);

 // Customer-master corrections and contact changes preserve approved project snapshots.
 const approvedCustomerBefore=await page.evaluate(async()=>JSON.stringify((await (await fetch('/api/projects/')).json()).results[0].current_approved.snapshot));
 await page.getByRole('button',{name:'Manage customers',exact:true}).click();await page.getByRole('button',{name:'Open customer Screen Review Customer',exact:true}).click();
 await page.getByRole('button',{name:'Add contact',exact:true}).click();await page.getByLabel('Contact name',{exact:true}).fill('Synthetic Primary Contact');await page.getByLabel('Contact relationship',{exact:true}).fill('Owner');await page.getByLabel('Contact email',{exact:true}).fill('primary@example.invalid');await page.getByLabel('Contact change note',{exact:true}).fill('Synthetic primary contact creation.');await page.getByRole('button',{name:'Create contact',exact:true}).click();await page.getByRole('status').filter({hasText:'Contact created.'}).waitFor();await page.getByText('Synthetic Primary Contact · Primary contact',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Add contact',exact:true}).click();await page.getByLabel('Contact name',{exact:true}).fill('Synthetic Second Contact');await page.getByLabel('Contact email',{exact:true}).fill('second@example.invalid');await page.getByLabel('Contact change note',{exact:true}).fill('Synthetic secondary contact creation.');await page.getByRole('button',{name:'Create contact',exact:true}).click();await page.getByRole('status').filter({hasText:'Contact created.'}).waitFor();await page.getByRole('button',{name:'Edit contact Synthetic Second Contact',exact:true}).click();await page.getByLabel('Primary contact for this customer',{exact:true}).check();await page.getByLabel('Replace Synthetic Primary Contact as primary contact. Keep their contact record.',{exact:true}).check();await page.getByLabel('Contact phone',{exact:true}).fill('301-555-0133');await page.getByLabel('Contact change note',{exact:true}).fill('Synthetic primary-contact replacement; preserve the former contact.');await page.getByRole('button',{name:'Save contact changes',exact:true}).click();await page.getByRole('status').filter({hasText:'Contact changes saved.'}).waitFor();await page.getByText('Synthetic Second Contact · Primary contact',{exact:true}).waitFor();assert.equal(await page.getByText('Synthetic Primary Contact · Primary contact',{exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Edit contact Synthetic Primary Contact',exact:true}).count(),1);
 await page.getByRole('button',{name:'Edit customer',exact:true}).click();await page.getByLabel('Customer legal name',{exact:true}).fill('Screen Review Customer Updated');await page.getByLabel('Customer billing address',{exact:true}).fill('25 Example Lane, Germantown, MD 20876');await page.getByLabel('Customer phone',{exact:true}).fill('301-555-0144');await page.getByLabel('Customer change note',{exact:true}).fill('Synthetic customer-master correction; preserve approved project versions.');await page.getByRole('button',{name:'Save customer changes',exact:true}).click();await page.getByRole('status').filter({hasText:'Customer changes saved.'}).waitFor();
 const approvedCustomerAfter=await page.evaluate(async()=>JSON.stringify((await (await fetch('/api/projects/')).json()).results[0].current_approved.snapshot));assert.equal(approvedCustomerAfter,approvedCustomerBefore,'Customer/contact changes must preserve the approved snapshot');
 await page.getByRole('button',{name:'Edit customer',exact:true}).click();await page.getByLabel('Customer archived — unavailable for new projects',{exact:true}).check();await page.getByLabel('Customer change note',{exact:true}).fill('Synthetic archive test; retain projects and contacts.');await page.getByRole('button',{name:'Save customer changes',exact:true}).click();await page.getByRole('status').filter({hasText:'Customer changes saved.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Add contact',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Edit customer',exact:true}).click();await page.getByLabel('Customer archived — unavailable for new projects',{exact:true}).uncheck();await page.getByLabel('Customer change note',{exact:true}).fill('Synthetic restore of archived customer.');await page.getByRole('button',{name:'Save customer changes',exact:true}).click();await page.getByRole('status').filter({hasText:'Customer changes saved.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Add contact',exact:true}).isDisabled(),false);await shot('20-customer-contacts');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Customer/contact mobile layout must fit');await shot('21-customer-contacts-mobile');await page.setViewportSize({width:1440,height:1000});


 // Scoped search and filters preserve approved details and expose all paginated results.
 await page.getByLabel('Search customers',{exact:true}).fill('Synthetic Second Contact');await page.getByRole('button',{name:'Search customers',exact:true}).click();await page.getByRole('status').filter({hasText:'1 customers found'}).waitFor();await page.getByRole('button',{name:'Open customer Screen Review Customer Updated',exact:true}).waitFor();
 await page.getByLabel('Customer status',{exact:true}).selectOption('ARCHIVED');await page.getByRole('button',{name:'Search customers',exact:true}).click();await page.getByText('No customers match these filters.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Clear customer filters',exact:true}).click();await page.getByRole('status').filter({hasText:'1 customers found'}).waitFor();
 execFileSync('python',[path.join(root,'backend/manage.py'),'shell','-c',`from core.models import Customer,Project,User; sales=User.objects.get(username='sales'); manager=User.objects.get(username='manager');
for n in range(55):
 c=Customer.objects.create(legal_name=f'ZSearch Customer {n:03}',billing_address=f'{n} Synthetic Search Street',created_by=sales); Project.objects.create(code=f'SYNTHETIC-SEARCH-{n:03}',customer=c,location=f'{n} Synthetic Search Site',sales_associate=sales,reviewer=manager)`],{env,stdio:'pipe'});
 await page.getByLabel('Search customers',{exact:true}).fill('ZSearch Customer');await page.getByRole('button',{name:'Search customers',exact:true}).click();await page.getByRole('status').filter({hasText:'55 customers found · Page 1'}).waitFor();await page.getByRole('button',{name:'Next customers',exact:true}).click();await page.getByRole('status').filter({hasText:'55 customers found · Page 2'}).waitFor();await page.getByRole('button',{name:'Open customer ZSearch Customer 054',exact:true}).waitFor();await shot('22-customer-search');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Customer search mobile layout must fit');await shot('23-customer-search-mobile');await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Back to projects',exact:true}).click();await page.getByLabel('Search projects',{exact:true}).fill('Screen Review Customer');await page.getByLabel('Project status',{exact:true}).selectOption('APPROVED');await page.getByRole('button',{name:'Search projects',exact:true}).click();await page.getByRole('status').filter({hasText:'1 projects found'}).waitFor();
 await page.getByLabel('Project status',{exact:true}).selectOption('CANCELLED');await page.getByRole('button',{name:'Search projects',exact:true}).click();await page.getByText('No projects match these filters.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Clear project filters',exact:true}).click();await page.getByRole('status').filter({hasText:'56 projects found'}).waitFor();await page.getByLabel('Search projects',{exact:true}).fill('SYNTHETIC-SEARCH');await page.getByLabel('Project status',{exact:true}).selectOption('DRAFT');await page.getByLabel('Project order',{exact:true}).selectOption('CODE');await page.getByRole('button',{name:'Search projects',exact:true}).click();await page.getByRole('status').filter({hasText:'55 projects found · Page 1'}).waitFor();await page.getByRole('button',{name:'Next projects',exact:true}).click();await page.getByRole('status').filter({hasText:'55 projects found · Page 2'}).waitFor();await page.locator('button.project').filter({hasText:'SYNTHETIC-SEARCH-054'}).waitFor();await shot('24-project-search');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Project search mobile layout must fit');await shot('25-project-search-mobile');await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('heading',{name:'New project',exact:true}).waitFor();assert.equal(await page.getByLabel('Customer',{exact:true}).locator('option').filter({hasText:'ZSearch Customer 054'}).count(),1,'Project customer choices must include customers beyond page 1');await page.getByRole('button',{name:'Close',exact:true}).click();

 // Audit records remain read-only, with recorded changes and current profile labels.
 assert.equal(await page.getByRole('button',{name:'Audit history',exact:true}).count(),0,'Manager must not see global audit history');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await signIn('comptroller');
 execFileSync('python',[path.join(root,'backend/manage.py'),'shell','-c',`from django.db import transaction; from core.models import User,Project; from core.services import audit; actor=User.objects.get(username='comptroller'); entity=Project.objects.get(code='SYNTHETIC-SEARCH-000');
with transaction.atomic():
 for n in range(51): audit(actor,'project.synthetic_review',entity.id,{'note':f'Synthetic pagination audit fixture {n}'})`],{env,stdio:'pipe'});
 await page.getByRole('button',{name:'Audit history',exact:true}).click();await page.getByRole('heading',{name:'Audit history',exact:true}).waitFor();
 await page.getByLabel('Search audit history',{exact:true}).fill('Synthetic customer-master correction');await page.getByLabel('Audit category',{exact:true}).selectOption('customer');await page.getByRole('button',{name:'Search audit history',exact:true}).click();await page.getByRole('status').filter({hasText:'1 audit records found'}).waitFor();await page.getByRole('heading',{name:'Customer · Updated',exact:true}).waitFor();await page.getByText('301-555-0100',{exact:true}).waitFor();await page.getByText('301-555-0144',{exact:true}).waitFor();assert.match(await page.locator('.audit-list').innerText(),/Changed by:.*manager/);await page.getByText('View recorded details',{exact:true}).click();await shot('26-audit-history');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Audit history mobile layout must fit');await shot('27-audit-history-mobile');await page.setViewportSize({width:1440,height:1000});
 await page.getByLabel('Audit start date',{exact:true}).fill('1900-01-01');await page.getByLabel('Audit end date',{exact:true}).fill('1900-01-01');await page.getByRole('button',{name:'Search audit history',exact:true}).click();await page.getByText('No audit records match these filters.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Clear audit filters',exact:true}).click();await page.getByRole('button',{name:'Next audit records',exact:true}).click();await page.getByRole('status').filter({hasText:'Page 2'}).waitFor();await page.getByRole('button',{name:'Previous audit records',exact:true}).click();await page.getByRole('status').filter({hasText:'Page 1'}).waitFor();
 await page.getByRole('button',{name:'Refresh audit history',exact:true}).click();await page.getByRole('status').filter({hasText:'Page 1'}).waitFor();await page.getByRole('button',{name:'Back to projects',exact:true}).click();await page.getByRole('button',{name:'Search projects',exact:true}).waitFor();
 assert.deepEqual(browserErrors,[]);console.log(`Screen review passed. Screenshots: ${shots}`);
} catch(e){if(page){await page.screenshot({path:path.join(work,'failure.png'),fullPage:true});console.error(await page.locator('body').innerText());console.error(`Failure screenshot: ${work}/failure.png`);}console.error(errors.slice(-5).join('\n'));throw e;}finally{await browser?.close();backend.kill();frontend.kill();}
