import { useEffect, useState } from 'react';
type API=<T>(path:string,method?:string,data?:unknown)=>Promise<T>;
type Event={id:string;sequence:number;actor:string|null;actor_username:string|null;actor_name:string;action:string;entity_id:string;created_at:string;payload:Record<string,unknown>};
type Page={count:number;next:string|null;previous:string|null;results:Event[];snapshot_sequence:number};
const categories:Record<string,string>={auth:'Authentication',access:'Access',customer:'Customer',contact:'Contact',account:'User account',project:'Project',msr:'Master sales record',document:'Document',signing:'Signing review',docusign:'Docusign account',sandbox:'Sandbox draft',release:'Release review',signing_test:'Sandbox signing test'};
const labels:Record<string,string>={is_active:'Account active',legal_name:'Customer legal name',primary:'Primary contact',archived:'Customer archived',role:'User role',billing_address:'Billing address'};
function label(key:string){return labels[key]||key.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());}
function object(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==='object'&&!Array.isArray(value);}
function valueText(value:unknown):string{if(value===undefined)return 'Not recorded';if(value===null)return 'None';if(value==='')return '(blank)';if(typeof value==='boolean')return value?'Yes':'No';return typeof value==='string'?value:JSON.stringify(value,null,2);}
function Changes({payload}:{payload:Record<string,unknown>}){
 const before=payload.before,after=payload.after;
 if(!object(before)||!object(after))return null;
 const keys=Array.from(new Set([...Object.keys(before),...Object.keys(after)])).filter(key=>JSON.stringify(before[key])!==JSON.stringify(after[key]));
 return keys.length?<div className="audit-changes"><h4>Recorded changes</h4>{keys.map(key=><div className="audit-change" key={key}><strong>{label(key)}</strong><div><span>Before</span><p>{valueText(before[key])}</p></div><div><span>After</span><p>{valueText(after[key])}</p></div></div>)}</div>:<p>No field differences were recorded.</p>;
}
export function AuditHistory({api,onBack}:{api:API;onBack:()=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[filters,setFilters]=useState({search:'',category:'',from:'',to:''}),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0);
 const [snapshot,setSnapshot]=useState<number|null>(null);
 const [data,setData]=useState<Page|null>(null),[error,setError]=useState('');
 useEffect(()=>{let closed=false;setData(null);setError('');api<Page>(`audit/?${new URLSearchParams({...filters,page:String(page),...(snapshot===null?{}:{through_sequence:String(snapshot)})})}`).then(d=>{if(!closed){setData(d);if(snapshot===null)setSnapshot(d.snapshot_sequence);}}).catch(e=>{if(!closed)setError(e.message);});return()=>{closed=true;};},[api,filters,page,refresh]);
 return <section className="audit-history" aria-labelledby="audit-heading"><div className="title"><div><h2 id="audit-heading">Audit history</h2><p className="muted">Recorded GECC changes and access events, newest first. Times and date filters use Eastern time. Actor IDs are recorded permanently; displayed names and usernames come from current account profiles. Role and source are recorded on new events; older events retain their original evidence.</p></div><button className="quiet" onClick={onBack}>Back to projects</button></div>
 <form className="record-filters audit-filters" onSubmit={e=>{e.preventDefault();setSnapshot(null);setPage(1);setFilters({search:query.trim(),category,from,to});}}>
  <label>Search audit history<input type="search" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Action, person, note, reason or record ID"/></label>
  <label>Audit category<select aria-label="Audit category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{Object.entries(categories).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>
  <label>Audit start date<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Audit end date<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>
  <div className="actions"><button>Search audit history</button><button className="quiet" type="button" onClick={()=>{setQuery('');setCategory('');setFrom('');setTo('');setSnapshot(null);setPage(1);setFilters({search:'',category:'',from:'',to:''});}}>Clear audit filters</button><button className="quiet" type="button" onClick={()=>{setSnapshot(null);setPage(1);setRefresh(n=>n+1);}}>Refresh audit history</button></div>
 </form>{error&&<p role="alert" className="error">{error}</p>}{data?<><p role="status">{data.count} audit records found · Page {page}</p>{data.count===0&&<p>No audit records match these filters.</p>}
 <ol className="audit-list">{data.results.map(event=>{const [group,verb]=event.action.split('.');const note=event.payload.note||event.payload.reason;return <li key={event.id}><h3>{categories[group]||label(group)} · {label(verb||event.action)}</h3><p><time dateTime={event.created_at}>{new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'long',timeZone:'America/New_York'}).format(new Date(event.created_at))}</time> · Event {event.sequence}</p><p><strong>Actor:</strong> {event.actor_name}{event.actor_username?` (${event.actor_username})`:""}</p><p><strong>Role at event:</strong> {object(event.payload._context)?valueText(event.payload._context.actor_role):"Not recorded on this historical event"} · <strong>Source:</strong> {object(event.payload._context)?valueText(event.payload._context.source):"Not recorded"}</p><p className="muted">Record ID: {event.entity_id}</p>{!!note&&<p className="audit-note"><strong>Recorded reason:</strong> {valueText(note)}</p>}{event.payload.password_changed===true&&<p>A local password reset was recorded. The password is not stored in this history.</p>}<Changes payload={event.payload}/>
 <details><summary>View recorded details</summary><p>Action: {event.action}<br/>Actor ID: {event.actor||"Unauthenticated"}<br/>Audit record ID: {event.id}</p><dl>{Object.entries(event.payload).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd>{valueText(value)}</dd></div>)}</dl></details></li>;})}</ol>
 <div className="actions"><button className="quiet" disabled={!data.previous} onClick={()=>setPage(n=>n-1)}>Previous audit records</button><button className="quiet" disabled={!data.next} onClick={()=>setPage(n=>n+1)}>Next audit records</button></div></>:!error&&<p>Loading audit history…</p>}</section>;
}
