import { useEffect, useState } from 'react';
type State = {ready_to_verify:boolean;configuration_blockers:string[];redirect_uri:string|null;verification:{account_name:string;verified_at:string;tokens_retained:boolean}|null;release_blockers:string[]};
type API = <T>(path:string,method?:string,data?:unknown)=>Promise<T>;
export function DocusignSetup({api,run,busy}:{api:API;run:(job:()=>Promise<void>)=>Promise<void>;busy:boolean}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState('');
 async function refresh(){setState(await api<State>('docusign/status/'));}
 useEffect(()=>{let cancelled=false;api<State>('docusign/status/').then(s=>{if(!cancelled)setState(s);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[api]);
 return <section className="docusign-setup"><details><summary>Docusign sandbox setup</summary><p className="muted">Verify the developer account using Docusign authorization. This development step sends no envelopes and retains no access or refresh tokens.</p>{error&&<p className="error" role="alert">{error}</p>}{state&&<>{state.verification&&<p>Account verified: {state.verification.account_name} · {new Date(state.verification.verified_at).toLocaleString()} (verification evidence only)</p>}{state.redirect_uri&&<p>Registered callback: {state.redirect_uri}</p>}{state.configuration_blockers.length>0&&<><p>Server configuration needed</p><ul>{state.configuration_blockers.map(b=><li key={b}>{b}</li>)}</ul></>}<div className="actions"><button className="quiet" disabled={busy} onClick={()=>void run(refresh)}>Refresh Docusign status</button><button disabled={busy||!state.ready_to_verify} onClick={()=>void run(async()=>{const next=await api<{authorization_url:string}>('docusign/connect/','POST',{});const url=new URL(next.authorization_url);if(url.origin!=='https://account-d.docusign.com'||url.pathname!=='/oauth/auth')throw new Error('Unexpected authorization destination.');window.location.assign(url.href);})}>Verify sandbox account</button></div><p className="muted">Live signing requires reusable credential storage, signer-ready document release, and verified provider status handling.</p></>}</details></section>;
}
