import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
type Person = {id:string;username:string;role:string};
type Customer = {id:string;legal_name:string;billing_address:string;archived:boolean};
type Line = {description:string;quantity:string};
type Snapshot = {customer:string;contact:string;billing_address:string;project_location:string;scope:string;equipment:Line[];materials:Line[];base_price:string;discount:string;tax:string;total_price:string;payment_option:string;payment_terms:string;commercial_notes:string};
type MSR = {id:string;number:number;status:string;snapshot:Snapshot;edit_sequence:number;revision_reason:string};
type Project = {id:string;code:string;location:string;state:string;current_approved:MSR|null;pending:MSR|null};
let token = '';
async function csrf(){ token = (await (await fetch('/api/csrf/')).json()).csrfToken; }
async function api<T>(path:string, method='GET', data?:unknown):Promise<T>{
  const response = await fetch(`/api/${path}`,{method,headers:{'Content-Type':'application/json','X-CSRFToken':token},body:data===undefined?undefined:JSON.stringify(data)});
  const body = await response.json();
  if(!response.ok) throw new Error(Object.entries(body).map(([key,value])=>`${key.replaceAll('_',' ')}: ${typeof value==='string'?value:JSON.stringify(value)}`).join(' '));
  return body;
}
function App(){
 const [user,setUser]=useState<Person|null>(null), [ready,setReady]=useState(false), [error,setError]=useState(''), [busy,setBusy]=useState(false);
 const [customers,setCustomers]=useState<Customer[]>([]), [people,setPeople]=useState<Person[]>([]), [projects,setProjects]=useState<Project[]>([]), [selected,setSelected]=useState<Project|null>(null);
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null), [reason,setReason]=useState(''), [history,setHistory]=useState<MSR[]>([]);
 const [panel,setPanel]=useState<'projects'|'customer'|'project'>('projects');
 async function run(job:()=>Promise<void>){setBusy(true);setError('');try{await job();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function load(){
  const [c,d,p]=await Promise.all([api<{results:Customer[]}>('customers/'),api<Person[]>('directory/'),api<{results:Project[]}>('projects/')]);
  setCustomers(c.results);setPeople(d);setProjects(p.results);
 }
 useEffect(()=>{void (async()=>{await csrf();try{setUser(await api<Person>('me/'));await load();}catch{/* A signed-out browser opens the login form. */}finally{setReady(true);}})();},[]);
 useEffect(()=>{
  if(!user)return;
  let last=0;
  const ping=()=>{if(Date.now()-last>60000){last=Date.now();void api('activity/','POST',{}).catch(()=>{setError('Your session expired. Sign in again.');setUser(null);});}};
  window.addEventListener('pointerdown',ping);window.addEventListener('keydown',ping);
  return()=>{window.removeEventListener('pointerdown',ping);window.removeEventListener('keydown',ping);};
 },[user]);
 function choose(p:Project){setSelected(p);setSnapshot(p.pending?.snapshot??null);setReason('');setHistory([]);}
 async function refresh(id?:string){await load();if(id){const p=await api<Project>(`projects/${id}/`);choose(p);}}
 async function change(action:string){if(!selected?.pending)return;await api(`msrs/${selected.pending.id}/transition/`,'POST',{action,expected_sequence:selected.pending.edit_sequence,snapshot,reason});await refresh(selected.id);}
 if(!ready)return <main><p>Opening workspace…</p></main>;
 if(!user)return <main className="login"><div className="brand">GECC <span>Project workspace</span></div><h1>Sign in</h1><p className="muted">Foundation development • local accounts</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await csrf();await api('dev-login/','POST',Object.fromEntries(f));await csrf();setUser(await api<Person>('me/'));await load();});}}><label>Username<input name="username" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button disabled={busy}>Sign in</button></form>{error&&<p role="alert" className="error">{error}</p>}</main>;
 const editable=selected?.state!=='CANCELLED' && selected?.pending && ['DRAFT','REJECTED'].includes(selected.pending.status);
 const approver=['SALES_MANAGER','COMPTROLLER'].includes(user.role);
 return <><header><div className="brand">GECC <span>Project workspace</span></div><div>{user.username} <span className="badge">{user.role.replaceAll('_',' ')}</span><button className="quiet" onClick={()=>void run(async()=>{await api('logout/','POST',{});setUser(null);setSelected(null);})}>Sign out</button></div></header><main>
 <div className="title"><div><p className="eyebrow">FOUNDATION / COMMERCIAL RECORDS</p><h1>Customers & projects</h1></div><div className="actions"><button className="quiet" onClick={()=>void run(()=>refresh(selected?.id))} disabled={busy}>Refresh</button>{['SALES_ASSOCIATE','SALES_MANAGER','COMPTROLLER'].includes(user.role)&&<><button onClick={()=>setPanel('customer')}>Add customer</button><button onClick={()=>setPanel('project')}>Create project</button></>}</div></div>
 {error&&<div role="alert" className="error">{error}</div>}
 {panel==='customer'&&<section><h2>New customer</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api('customers/','POST',Object.fromEntries(f));await load();setPanel('projects');});}}><div className="grid"><label>Legal name<input name="legal_name" required/></label><label>Billing address<input name="billing_address" required/></label><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone"/></label><label>Duplicate override reason (if needed)<input name="duplicate_reason"/></label></div><button disabled={busy}>Save customer</button><button type="button" className="quiet" onClick={()=>setPanel('projects')}>Close</button></form></section>}
 {panel==='project'&&<section><h2>New project</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const p=await api<Project>('projects/','POST',Object.fromEntries(f));await load();choose(p);setPanel('projects');});}}><div className="grid"><label>Customer<select name="customer" required defaultValue=""><option value="">Choose customer</option>{customers.filter(c=>!c.archived).map(c=><option key={c.id} value={c.id}>{c.legal_name}</option>)}</select></label><label>Installation address<input name="location" required/></label><label>Sales Associate<select name="sales_associate" required defaultValue={user.role==='SALES_ASSOCIATE'?user.id:''}><option value="">Choose associate</option>{people.filter(p=>p.role==='SALES_ASSOCIATE').map(p=><option key={p.id} value={p.id}>{p.username}</option>)}</select></label><label>Sales Manager<select name="reviewer" required defaultValue={user.role==='SALES_MANAGER'?user.id:''}><option value="">Choose reviewer</option>{people.filter(p=>p.role==='SALES_MANAGER').map(p=><option key={p.id} value={p.id}>{p.username}</option>)}</select></label><label>Duplicate override reason (if needed)<input name="duplicate_reason"/></label></div><button disabled={busy}>Create draft</button><button type="button" className="quiet" onClick={()=>setPanel('projects')}>Close</button></form></section>}
 <div className="workspace"><aside><h2>Projects <small>{projects.length}</small></h2>{projects.length===0&&<p className="muted">Create a customer and project to begin.</p>}{projects.map(p=><button className={`project ${selected?.id===p.id?'active':''}`} key={p.id} onClick={()=>choose(p)}><strong>{p.code}</strong><span>{p.location}</span><span className="badge">{p.state}</span></button>)}</aside>
 <article>{!selected?<section className="empty"><h2>Your commercial workspace</h2><p>Select a project to prepare its Master Sales Record or review an approval.</p></section>:<><section><div className="title"><div><h2>{selected.code}</h2><p className="muted">{selected.location}</p></div><span className="badge">{selected.state}</span></div>
 <div className="versionbar"><span>Approved: {selected.current_approved?`Version ${selected.current_approved.number}.0`:'None yet'}</span><span>Pending: {selected.pending?`Version ${selected.pending.number}.0 • ${selected.pending.status}`:'None'}</span><button className="quiet" onClick={()=>void run(async()=>setHistory(await api<MSR[]>(`projects/${selected.id}/history/`)))}>Version history</button></div>
 {selected.current_approved&&<details><summary>View approved version {selected.current_approved.number}.0</summary><Summary data={selected.current_approved.snapshot}/></details>}
 {history.map(v=><details key={v.id}><summary>Version {v.number}.0 • {v.status}</summary><p>{v.revision_reason}</p><Summary data={v.snapshot}/></details>)}
 {selected.pending&&snapshot?<><h3>Master Sales Record • Version {selected.pending.number}.0</h3><fieldset disabled={!editable||busy}><div className="grid">{(['customer','contact','billing_address','project_location','scope','base_price','discount','tax','total_price','payment_terms','commercial_notes'] as const).map(key=><label key={key}>{({customer:'Customer name',contact:'Contact',billing_address:'Billing address',project_location:'Installation address',scope:'Scope of work',base_price:'Base price ($)',discount:'Discount ($)',tax:'Tax ($)',total_price:'Total price ($)',payment_terms:'Payment terms',commercial_notes:'Commercial notes'})[key]}{['scope','payment_terms','commercial_notes'].includes(key)?<textarea value={snapshot[key]} onChange={e=>setSnapshot({...snapshot,[key]:e.target.value})}/>:<input value={snapshot[key]} onChange={e=>setSnapshot({...snapshot,[key]:e.target.value})}/>}</label>)}<label>Payment option<select value={snapshot.payment_option} onChange={e=>setSnapshot({...snapshot,payment_option:e.target.value})}><option value="50_PERCENT_DEPOSIT">50% deposit / 50% at completion</option><option value="100_PERCENT_COMPLETION">100% at completion</option></select></label></div><Lines title="Equipment" items={snapshot.equipment} onChange={items=>setSnapshot({...snapshot,equipment:items})}/><Lines title="Materials" items={snapshot.materials} onChange={items=>setSnapshot({...snapshot,materials:items})}/></fieldset><p className="muted">Installation eligibility: five calendar days after the later customer contract or invoice signature, and after the applicable cancellation deadline. Required signatures and verified deposit also apply.</p><div className="actions">{editable&&<><button disabled={busy} onClick={()=>void run(()=>change('edit'))}>Save draft</button><button disabled={busy} onClick={()=>void run(async()=>{await api(`msrs/${selected.pending!.id}/transition/`,'POST',{action:'edit',expected_sequence:selected.pending!.edit_sequence,snapshot});const p=await api<Project>(`projects/${selected.id}/`);choose(p);await api(`msrs/${p.pending!.id}/transition/`,'POST',{action:'submit',expected_sequence:p.pending!.edit_sequence});await refresh(selected.id);})}>Save & submit</button></>}{selected.state!=='CANCELLED'&&selected.pending.status==='SUBMITTED'&&approver&&<><button disabled={busy} onClick={()=>void run(()=>change('approve'))}>Approve version</button><button disabled={busy||!reason.trim()} className="quiet" onClick={()=>void run(()=>change('reject'))}>Reject with reason</button></>}</div></>:<p className="muted">The approved record is locked. Create a revision to change any commercial field.</p>}
 <label>Review note / revision reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{selected.state!=='CANCELLED'&&selected.current_approved&&!selected.pending&&<button disabled={busy||!reason.trim()} onClick={()=>void run(async()=>{await api(`projects/${selected.id}/revision/`,'POST',{reason,expected_approved_id:selected.current_approved!.id});await refresh(selected.id);})}>Create revision</button>}
 {approver&&<button className="quiet" disabled={busy||!reason.trim()} onClick={()=>void run(async()=>{await api(`projects/${selected.id}/state/`,'POST',{action:selected.state==='CANCELLED'?'reopen':'cancel',reason,expected_state:selected.state});await refresh(selected.id);})}>{selected.state==='CANCELLED'?'Reopen project':'Cancel project'}</button>}
 </section></>}</article></div><footer>GECC foundation development • Signing and payment verification are not connected yet.</footer></main></>;
}
function Lines({title,items,onChange}:{title:string;items:Line[];onChange:(items:Line[])=>void}){return <div><h3>{title}</h3>{items.map((item,i)=><div className="line" key={i}><label>Description<input value={item.description} onChange={e=>onChange(items.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/></label><label>Quantity<input value={item.quantity} onChange={e=>onChange(items.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))}/></label><button type="button" className="quiet" onClick={()=>onChange(items.filter((_,n)=>n!==i))}>Remove</button></div>)}<button type="button" className="quiet" onClick={()=>onChange([...items,{description:'',quantity:'1'}])}>Add {title.toLowerCase()} item</button></div>;}
function Summary({data}:{data:Snapshot}){return <dl>{Object.entries(data).map(([k,v])=><React.Fragment key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{Array.isArray(v)?v.map(x=>`${x.description} × ${x.quantity}`).join('; ')||'None':v}</dd></React.Fragment>)}</dl>;}
createRoot(document.getElementById('root')!).render(<App/>);
