import { useEffect, useState } from 'react';
import { SigningTest } from './SigningTest';
type API = <T>(path:string,method?:string,data?:unknown)=>Promise<T>;
type Run = (job:()=>Promise<void>)=>Promise<void>;
type Evidence={id:string;kind:string;data:{verified:boolean;deadline?:string;completion_date?:string;source_reference:string}};
export function VerificationEvidence({msrId,comptroller,busy,api,run}:{msrId:string;comptroller:boolean;busy:boolean;api:API;run:Run}){
 const [rows,setRows]=useState<Evidence[]>([]),[kind,setKind]=useState('CANCELLATION_DEADLINE'),[verified,setVerified]=useState(true),[error,setError]=useState('');const path=`msrs/${msrId}/verification-evidence/`;
 useEffect(()=>{let closed=false;api<Evidence[]>(path).then(r=>{if(!closed)setRows(r);}).catch(e=>{if(!closed)setError(e.message);});return()=>{closed=true;};},[path,api]);
 return <details className="verification-evidence"><summary>Project verification evidence</summary><p>Manual verification records are bound to this approved MSR. The app records your attestation; it does not independently verify the referenced evidence. Sending remains disabled.</p>{error&&<p role="alert" className="error">{error}</p>}
 <button type="button" className="quiet" disabled={busy} onClick={()=>void run(async()=>setRows(await api<Evidence[]>(path)))}>Refresh verification evidence</button>
 <ul>{rows.map(r=><li key={r.id}>{r.kind.replaceAll('_',' ')} · {r.data.verified?'Recorded verification':'Withdrawn'} · {r.data.deadline||r.data.completion_date||''} · {r.data.source_reference}</li>)}</ul>
 {comptroller&&<form key={kind} onSubmit={e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(e.currentTarget));const data:{[key:string]:unknown}={...fields,kind,verified};for(const k of ['notice_and_applicability_checked','work_verified','permits_inspections_checked','exceptions_resolved'])data[k]=fields[k]==='on';void run(async()=>{await api(path,'POST',data);setRows(await api<Evidence[]>(path));});}}><div className="grid"><label>Evidence type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="CANCELLATION_DEADLINE">Cancellation deadline</option><option value="WORK_COMPLETION">Work completion</option></select></label><label>Evidence reference<input name="source_reference" maxLength={2000} required/></label><label>Verification note<textarea name="verification_note" maxLength={2000} required/></label></div>
 <label className="sandbox-confirm"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Record verification (clear to withdraw the previous verification)</label>
 {verified&&(kind==='CANCELLATION_DEADLINE'?<><label>Exact cancellation deadline with UTC offset<input name="deadline" placeholder="YYYY-MM-DDTHH:MM:SS-04:00" required/></label><label className="sandbox-confirm"><input type="checkbox" name="notice_and_applicability_checked" required/>I reviewed applicable cancellation rights, notice delivery and the exact deadline against the evidence reference.</label></>:<><label>Verified work-completion date<input type="date" name="completion_date" required/></label><label>Installation Manager unavailable — verification substitute reason<textarea name="substitute_reason" required/></label>{[['work_verified','I verified the approved scope of work is complete.'],['permits_inspections_checked','I reviewed applicable permits and inspections.'],['exceptions_resolved','I verified outstanding exceptions are resolved.']].map(([name,text])=><label className="sandbox-confirm" key={name}><input type="checkbox" name={name} required/>{text}</label>)}</>)}<p>The Comptroller records completion verification as an authorized substitute in this slice; direct Installation Manager operational access is still pending.</p><button disabled={busy}>Save verification evidence</button></form>}
 </details>;
}
const packageDate = new Intl.DateTimeFormat('en-US', {timeZone:'America/New_York',year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit',timeZoneName:'short'});
type Package={id:string;created_at:string;created_by:string;release:{status:string;blockers:string[]};documents:{kind:string;download_url:string}[];decisions:{decision:string;note:string}[]};
export function ReleaseReview({planId,current,actorId,comptroller,busy,api,run}:{planId:string;current:boolean;actorId:string;comptroller:boolean;busy:boolean;api:API;run:Run}){
 const [packages,setPackages]=useState<Package[]>([]),[error,setError]=useState('');const path=`signing-reviews/${planId}/release-packages/`;
 useEffect(()=>{let closed=false;api<Package[]>(path).then(p=>{if(!closed)setPackages(p);}).catch(e=>{if(!closed)setError(e.message);});return()=>{closed=true;};},[path,api]);
 return <div className="sandbox-package"><h4>Release document review</h4><p>This separate review uses recorded cancellation or completion evidence. A different authorized person must approve the package. Approval does not enable sending.</p>{error&&<p role="alert" className="error">{error}</p>}
 {current&&<button className="quiet" type="button" disabled={busy} onClick={()=>void run(async()=>{await api(path,'POST',{});setPackages(await api<Package[]>(path));})}>Prepare release review package</button>}
 <button className="quiet" type="button" disabled={busy} onClick={()=>void run(async()=>setPackages(await api<Package[]>(path)))}>Refresh release review</button>
 {packages.map(pkg=><div key={pkg.id}><p><time dateTime={pkg.created_at} title="Package creation date and time">{packageDate.format(new Date(pkg.created_at))}</time> · Release review: <strong>{pkg.release.status.replaceAll('_',' ')}</strong></p><ul>{pkg.documents.map(d=><li key={d.kind}><a href={d.download_url}>Download release {d.kind.toLowerCase().replaceAll('_',' ')}</a></li>)}</ul>{pkg.release.blockers.map(b=><p key={b}>{b}</p>)}{pkg.decisions.map((d,i)=><p key={i}>{d.decision} · {d.note}</p>)}
 {current&&pkg.release.status!=='BLOCKED'&&<form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await api(`release-packages/${pkg.id}/decisions/`,'POST',{...f,documents_and_evidence_reviewed:f.documents_and_evidence_reviewed==='on'});setPackages(await api<Package[]>(path));});}}><label>Release decision<select name="decision"><option value="APPROVED">Approve reviewed package</option><option value="REVOKED">Revoke approval</option></select></label><label>Release review note<textarea name="note" required maxLength={2000}/></label><label className="sandbox-confirm"><input type="checkbox" name="documents_and_evidence_reviewed"/>I reviewed these exact documents, recipient identities, routing and referenced verification evidence.</label>{pkg.created_by===actorId&&<p>Approval requires another authorized reviewer; you can record a revocation.</p>}<button disabled={busy}>Record release decision</button></form>}<SigningTest sourceId={pkg.id} sourceApproved={pkg.release.status==='APPROVED'} comptroller={comptroller} actorId={actorId} busy={busy} api={api} run={run}/></div>)}
 </div>;
}
