import { useEffect, useState } from 'react';
type API = <T>(path:string, method?:string, data?:unknown)=>Promise<T>;
type Package = {id:string;documents:{kind:string;download_url:string}[];attempt:null|{state:string;envelope_id:string;evidence:{visual_review_required?:boolean};observations?:{id:string;evidence:{outcome:string;observed_at:string;metadata_matched:boolean;provider_status?:string;blockers:string[]}}[]}};
export function SandboxPackage({planId,current,comptroller,busy,api,run}:{planId:string;current:boolean;comptroller:boolean;busy:boolean;api:API;run:(job:()=>Promise<void>)=>Promise<void>}){
 const [checkConfirmed,setCheckConfirmed]=useState(false);
 const [pkg,setPackage]=useState<Package|null>(null),[confirmed,setConfirmed]=useState(false),[error,setError]=useState('');
 const path=`signing-reviews/${planId}/sandbox-package/`;
 useEffect(()=>{let closed=false;api<Package|null>(path).then(p=>{if(!closed)setPackage(p);}).catch(e=>{if(!closed)setError(e.message);});return()=>{closed=true;};},[path,api]);
 return <div className="sandbox-package"><h4>Sandbox draft test</h4><p>Test copies use the reviewed signer names and preserve the approved project details. They are marked DO NOT SIGN. Cancellation deadlines and completed work remain unverified; live release is blocked.</p>{error&&<p role="alert" className="error">{error}</p>}
 {current&&<button type="button" className="quiet" disabled={busy} onClick={()=>void run(async()=>{setError('');setPackage(await api<Package>(path,'POST',{}));})}>Prepare sandbox package</button>}
 {pkg&&<><ul>{pkg.documents.map(d=><li key={d.kind}><a href={d.download_url}>Download sandbox {d.kind.toLowerCase().replaceAll('_',' ')}</a></li>)}</ul>
 {pkg.attempt&&<p>Draft attempt: <strong>{pkg.attempt.state.replaceAll('_',' ')}</strong>{pkg.attempt.envelope_id&&<> · Envelope {pkg.attempt.envelope_id}</>}{pkg.attempt.state==='RECONCILIATION_REQUIRED'&&' — inspect your existing Docusign sandbox drafts; do not create another copy.'}{pkg.attempt.evidence.visual_review_required&&' — inspect document appearance and tab placement in Docusign Drafts. This does not approve sending.'}</p>}
 <button type="button" className="quiet" disabled={busy} onClick={()=>void run(async()=>setPackage(await api<Package>(path)))}>Refresh sandbox draft status</button>
 {pkg.attempt?.observations?.map(o=><div key={o.id}><p>Sandbox check: <strong>{o.evidence.outcome}</strong> · {new Date(o.evidence.observed_at).toLocaleString()}{o.evidence.provider_status&&<> · Provider status: {o.evidence.provider_status}</>}</p><ul>{o.evidence.blockers.map(b=><li key={b}>{b}</li>)}</ul></div>)}
 {comptroller&&pkg.attempt?.envelope_id&&['DRAFT_VALIDATED','CREATED_UNVALIDATED','RECONCILIATION_REQUIRED','RECHECK_PENDING'].includes(pkg.attempt.state)&&<><p>This checks the existing sandbox envelope's status, recipient identities, routing, document names and field positions. It does not compare provider PDF bytes or approve sending. Results describe the time of inspection; visual review is still required. Superseded project reviews remain blocked.</p><label><input type="checkbox" checked={checkConfirmed} onChange={e=>setCheckConfirmed(e.target.checked)}/>I authorize a read-only check of this existing sandbox draft.</label><button type="button" disabled={busy||!checkConfirmed} onClick={()=>void run(async()=>{const result=await api<{authorization_url:string}>(`sandbox-packages/${pkg.id}/connect-check/`,'POST',{confirm_read_only_check:true});const url=new URL(result.authorization_url);if(url.origin!=='https://account-d.docusign.com'||url.pathname!=='/oauth/auth')throw Error('Unexpected sandbox authorization URL.');window.location.assign(url.href);})}>Check existing sandbox draft</button></>}
 {pkg.attempt?.state==='RECHECK_PENDING'&&<p>Read-only check pending. Finish authorization, or start a fresh check if authorization expired or failed. Earlier validation is historical.</p>}

 {current&&comptroller&&(!pkg.attempt||pkg.attempt.state==='AUTH_PENDING')&&<><label className="sandbox-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I authorize creation of one unsent draft in the configured Docusign sandbox for testing.</label><button type="button" disabled={busy||!confirmed} onClick={()=>void run(async()=>{const result=await api<{authorization_url:string}>(`sandbox-packages/${pkg.id}/connect-draft/`,'POST',{confirm_unsent_sandbox_draft:true});const url=new URL(result.authorization_url);if(url.origin!=='https://account-d.docusign.com'||url.pathname!=='/oauth/auth')throw Error('Unexpected sandbox authorization URL.');window.location.assign(url.href);})}>Authorize unsent sandbox draft</button></>}
 {!comptroller&&current&&<p>The Comptroller authorizes Docusign sandbox draft creation.</p>}</>}
 </div>;
}
