import { useEffect, useState } from 'react';
type Signer = {id:string;name:string;email:string;role:string};
type Plan = {id:string;group:string;review:{msr_version:number;customer:{name:string;email:string};gecc:{name:string;email:string;role:string};substitute_reason:string;envelope_preview:{recipients:{signers:{routingOrder:string;name:string;email:string}[]}}};release:{status:string;release_blockers:string[]}};
type API = <T>(path:string, method?:string, data?:unknown)=>Promise<T>;
export function SigningReview({projectId,msrId,finance,active,approver,busy,api,run}:{projectId:string;msrId?:string;finance?:string;active:boolean;approver:boolean;busy:boolean;api:API;run:(job:()=>Promise<void>)=>Promise<void>}){
 const [plans,setPlans]=useState<Plan[]>([]),[signers,setSigners]=useState<Signer[]>([]),[group,setGroup]=useState('COMMERCIAL'),[loadError,setLoadError]=useState('');
 useEffect(()=>{let cancelled=false;setPlans([]);setLoadError('');api<Plan[]>(`projects/${projectId}/signing-reviews/`).then(p=>{if(!cancelled)setPlans(p);}).catch(e=>{if(!cancelled)setLoadError(e.message);});return()=>{cancelled=true;};},[projectId,msrId,active,api]);
 useEffect(()=>{let cancelled=false;setSigners([]);if(approver)api<Signer[]>(`projects/${projectId}/signing-candidates/?group=${group}`).then(p=>{if(!cancelled)setSigners(p);}).catch(e=>{if(!cancelled)setLoadError(e.message);});return()=>{cancelled=true;};},[projectId,group,approver,api]);
 return <div className="documents"><h3>Signing review</h3><p className="muted">Review recipients and routing before connecting Docusign. Unsigned requests expire 75 calendar days after first send. Completed signatures do not expire.</p>{loadError&&<p role="alert" className="error">{loadError}</p>}
 {msrId&&active&&approver&&<form key={`${projectId}-${msrId}-${group}`} onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await api(`msrs/${msrId}/signing-reviews/`,'POST',{...data,group});setPlans(await api<Plan[]>(`projects/${projectId}/signing-reviews/`));});}}><div className="grid">
 <label>Signing workflow<select aria-label="Signing workflow" value={group} onChange={e=>{setGroup(e.target.value);setLoadError('');}}><option value="COMMERCIAL">Contract and invoice — customer first</option>{finance&&<option value={`COMPLETION_${finance}`}>Completion certificate — GECC first</option>}</select></label>
 <label>Customer signer full name<input name="customer_name" maxLength={250} required/></label><label>Customer signer email<input name="customer_email" type="email" maxLength={254} required/></label>
 <label>GECC signer<select name="gecc_signer" aria-label="GECC signer" required defaultValue=""><option value="">Choose signer</option>{signers.filter(s=>s.name).map(s=><option key={s.id} value={s.id}>{s.name} · {s.role.replaceAll('_',' ')}</option>)}</select></label>
 <label>Signer identity and authority review<textarea name="authority_note" maxLength={2000} required placeholder="Record how you checked the customer signer's email and authority to sign."/></label>
 {group!=='COMMERCIAL'&&<label>Installation Manager unavailable — substitute reason<textarea name="substitute_reason" maxLength={2000} placeholder="Required when the Comptroller signs in place of the Installation Manager."/></label>}
 </div><p className="muted">Prepare the workflow's PDFs first. GECC signer accounts need a full name and email.{group!=='COMMERCIAL'&&' Work completion must be verified before release.'}</p><button disabled={busy}>Save signing review</button></form>}
 {plans.map(plan=><details key={plan.id} className="signing-review"><summary>MSR {plan.review.msr_version}.0 · {plan.group.replaceAll('_',' ')} · {plan.release.status.replaceAll('_',' ')}</summary><ol>{[...plan.review.envelope_preview.recipients.signers].sort((a,b)=>Number(a.routingOrder)-Number(b.routingOrder)).map(s=><li key={s.routingOrder}>{s.name} — {s.email}</li>)}</ol>{plan.review.substitute_reason&&<p>GECC substitute reason: {plan.review.substitute_reason}</p>}<p>Release checks</p><ul>{plan.release.release_blockers.map(b=><li key={b}>{b}</li>)}</ul><button disabled>Send for signatures</button></details>)}
 </div>;
}
