import { useEffect, useState } from 'react';
type API=<T>(path:string,method?:string,data?:unknown)=>Promise<T>;
type Props={sourceId:string;sourceApproved:boolean;comptroller:boolean;actorId:string;busy:boolean;api:API;run:(job:()=>Promise<void>)=>Promise<void>};
type Test={id:string;created_at:string;created_by:string;status:string;customer:{name:string;email:string};gecc:{name:string;email:string};test_note:string;blockers:string[];configuration_blockers:string[];send_available:boolean;documents:{kind:string;download_url:string}[];decisions:{decision:string;note:string}[];attempt:null|{state:string;envelope_id:string;observations:{id:string;evidence:{outcome:string;observed_at:string;provider_status?:string;blockers:string[];local_review_blockers:string[]}}[];retained_documents:{kind:string;download_url:string;pdf_sha256:string}[]}};
const dates=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit',timeZoneName:'short'});
export function SigningTest({sourceId,sourceApproved,comptroller,actorId,busy,api,run}:Props){
 const [tests,setTests]=useState<Test[]>([]),[error,setError]=useState('');const path=`release-packages/${sourceId}/signing-tests/`;
 useEffect(()=>{let closed=false;api<Test[]>(path).then(p=>{if(!closed)setTests(p);}).catch(e=>{if(!closed)setError(e.message);});return()=>{closed=true;};},[path,api]);
 async function refresh(){setTests(await api<Test[]>(path));}
 async function connect(id:string,operation:'SEND'|'READ'){const result=await api<{authorization_url:string}>(`signing-tests/${id}/connect/`,'POST',{operation,confirmed:true});const u=new URL(result.authorization_url);if(u.origin!=='https://account-d.docusign.com'||u.pathname!=='/oauth/auth')throw Error('Unexpected sandbox authorization URL.');window.location.assign(u.href);}
 return <details className="signing-test"><summary>Sandbox signing test</summary><p>Use a fictional project and two email addresses you control. This creates separate PDFs marked SANDBOX SIGNING TEST. A different authorized person must approve these exact test PDFs and recipient emails before the Comptroller can send an invitation. Production sending stays disabled.</p>{error&&<p role="alert" className="error">{error}</p>}
 {sourceApproved&&comptroller&&<form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await api(path,'POST',{...f,fictional_project_confirmed:f.fictional_project_confirmed==='on',emails_controlled:f.emails_controlled==='on'});await refresh();});}}><label>Customer test email<input name="customer_email" type="email" required/></label><label>GECC test email<input name="gecc_email" type="email" required/></label><label>Signing-test preparation note<textarea name="test_note" required maxLength={2000}/></label><p>Both emails must be in the backend's configured test allowlist. These test addresses replace the fictional addresses for this package only.</p><label className="sandbox-confirm"><input name="fictional_project_confirmed" type="checkbox" required/>This is a fictional project used only to test the software.</label><label className="sandbox-confirm"><input name="emails_controlled" type="checkbox" required/>I control both test email addresses and authorize their use for this test.</label><button disabled={busy}>Prepare signing-test package</button></form>}
 <button type="button" className="quiet" disabled={busy} onClick={()=>void run(refresh)}>Refresh signing-test status</button>
 {tests.map(t=><div className="signing-test-package" key={t.id}><p><time dateTime={t.created_at}>{dates.format(new Date(t.created_at))}</time> · Signing-test review: <strong>{t.status.replaceAll('_',' ')}</strong></p><p>{t.customer.name} — {t.customer.email}<br/>{t.gecc.name} — {t.gecc.email}</p><p>{t.test_note}</p><ul>{t.documents.map(d=><li key={d.kind}><a href={d.download_url}>Download signing-test {d.kind.toLowerCase().replaceAll('_',' ')}</a></li>)}</ul>{t.blockers.map(b=><p key={b}>{b}</p>)}{t.decisions.map((d,i)=><p key={i}>{d.decision} · {d.note}</p>)}
 {sourceApproved&&<form onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await api(`signing-tests/${t.id}/decisions/`,'POST',{...f,exact_test_reviewed:f.exact_test_reviewed==='on'});await refresh();});}}><label>Signing-test decision<select name="decision"><option value="APPROVED">Approve signing test</option><option value="REVOKED">Revoke signing-test approval</option></select></label><label>Signing-test review note<textarea name="note" required maxLength={2000}/></label><label className="sandbox-confirm"><input name="exact_test_reviewed" type="checkbox"/>I reviewed these exact signing-test PDFs, controlled email addresses, names and routing.</label>{t.created_by===actorId&&<p>Another authorized person must approve this signing-test package.</p>}<button disabled={busy}>Record signing-test decision</button></form>}
 {t.configuration_blockers.map(b=><p key={b}>{b}</p>)}
 {comptroller&&t.send_available&&<form onSubmit={e=>{e.preventDefault();void run(()=>connect(t.id,'SEND'));}}><label className="sandbox-confirm"><input type="checkbox" required/>I authorize one actual sandbox signing invitation to each reviewed test email address. This is a fictional software test.</label><button disabled={busy}>Authorize sandbox signing test</button></form>}
 {t.attempt&&<><p>Signing-test attempt: <strong>{t.attempt.state.replaceAll('_',' ')}</strong>{t.attempt.envelope_id&&<> · Envelope {t.attempt.envelope_id}</>}</p>{t.attempt.state==='SEND_UNCERTAIN'&&<p>The send result is uncertain. Do not create or send another package. Inspect this attempt before proceeding.</p>}{t.attempt.observations.map(o=><div key={o.id}><p>Signing-test check: <strong>{o.evidence.outcome.replaceAll('_',' ')}</strong> · {dates.format(new Date(o.evidence.observed_at))} · {o.evidence.provider_status||'Status unavailable'}</p>{[...o.evidence.blockers,...o.evidence.local_review_blockers].map((b,i)=><p key={i}>{b}</p>)}</div>)}<ul>{t.attempt.retained_documents.map(d=><li key={d.kind}><a href={d.download_url}>Download retained sandbox {d.kind.toLowerCase().replaceAll('_',' ')}</a></li>)}</ul>
 {comptroller&&t.attempt.envelope_id&&t.attempt.state!=='NETWORK_STARTED'&&<form onSubmit={e=>{e.preventDefault();void run(()=>connect(t.id,'READ'));}}><label className="sandbox-confirm"><input type="checkbox" required/>I authorize a read-only status check and retention of completed sandbox PDFs and the Docusign completion certificate.</label><button disabled={busy}>Check signing-test status and retain completed PDFs</button></form>}</>}
 </div>)}
 </details>;
}
