# Generated by Django 5.2.17 on 2026-10-04 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE TRIGGER gecc_document_guard BEFORE UPDATE OR DELETE ON core_document FOR EACH ROW EXECUTE FUNCTION gecc_audit_guard()")
    else:
        for action in ['UPDATE', 'DELETE']:
            schema_editor.execute(f"CREATE TRIGGER gecc_document_{action.lower()} BEFORE {action} ON core_document BEGIN SELECT RAISE(ABORT, 'Generated documents are immutable'); END")

def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER gecc_document_guard ON core_document')
    else:
        for action in ['update', 'delete']:
            schema_editor.execute(f'DROP TRIGGER gecc_document_{action}')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_safeguards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('CONTRACT', 'Project SOW agreement'), ('INVOICE', 'HVAC invoice'), ('COMPLETION_FINANCED', 'Financed completion certificate'), ('COMPLETION_NON_FINANCED', 'Non-financed completion certificate')], max_length=32)),
                ('status', models.CharField(default='PREPARATION', max_length=20)),
                ('filename', models.CharField(max_length=200)),
                ('template_sha256', models.CharField(max_length=64)),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('renderer_version', models.CharField(max_length=20)),
                ('values', models.JSONField()),
                ('content', models.BinaryField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('msr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.msr')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('msr', 'kind', 'template_sha256', 'renderer_version'), name='document_generation_unique')],
            },
        ),
        migrations.RunPython(guards, remove_guards),
    ]
