# Generated by Django 5.2.17 on 2026-10-04 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE TRIGGER gecc_signingplan_guard BEFORE UPDATE OR DELETE ON core_signingplan FOR EACH ROW EXECUTE FUNCTION gecc_audit_guard()")
    else:
        for action in ['UPDATE', 'DELETE']:
            schema_editor.execute(f"CREATE TRIGGER gecc_signingplan_{action.lower()} BEFORE {action} ON core_signingplan BEGIN SELECT RAISE(ABORT, 'Signing reviews are immutable'); END")

def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER gecc_signingplan_guard ON core_signingplan')
    else:
        for action in ['update', 'delete']:
            schema_editor.execute(f'DROP TRIGGER gecc_signingplan_{action}')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(max_length=32)),
                ('review', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('msr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_plans', to='core.msr')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('msr', 'group', 'digest'), name='signing_review_unique')],
            },
        ),
        migrations.RunPython(guards, remove_guards),
    ]
