# Generated by Django 5.2.17 on 2026-10-05 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE TRIGGER gecc_docusignverification_guard BEFORE UPDATE OR DELETE ON core_docusignverification FOR EACH ROW EXECUTE FUNCTION gecc_audit_guard()")
    else:
        for action in ['UPDATE', 'DELETE']:
            schema_editor.execute(f"CREATE TRIGGER gecc_docusignverification_{action.lower()} BEFORE {action} ON core_docusignverification BEGIN SELECT RAISE(ABORT, 'Docusign verification evidence is immutable'); END")

def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER gecc_docusignverification_guard ON core_docusignverification')
    else:
        for action in ['update', 'delete']:
            schema_editor.execute(f'DROP TRIGGER gecc_docusignverification_{action}')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_signingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocusignChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state_digest', models.CharField(max_length=64, unique=True)),
                ('session_digest', models.CharField(max_length=64)),
                ('configuration_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocusignVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.docusignchallenge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(guards, remove_guards),
    ]
