# Generated by Django 5.2.17 on 2026-10-06 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE TRIGGER gecc_sandboxpackage_guard BEFORE UPDATE OR DELETE ON core_sandboxpackage FOR EACH ROW EXECUTE FUNCTION gecc_audit_guard()")
    else:
        for action in ['UPDATE', 'DELETE']:
            schema_editor.execute(f"CREATE TRIGGER gecc_sandboxpackage_{action.lower()} BEFORE {action} ON core_sandboxpackage BEGIN SELECT RAISE(ABORT, 'Sandbox packages are immutable'); END")


def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER gecc_sandboxpackage_guard ON core_sandboxpackage')
    else:
        for action in ['update', 'delete']:
            schema_editor.execute(f'DROP TRIGGER gecc_sandboxpackage_{action}')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_docusignchallenge_docusignverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusignchallenge',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='SandboxPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sandbox_package', to='core.signingplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SandboxAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(default='AUTH_PENDING', max_length=32)),
                ('account_id', models.CharField(max_length=36)),
                ('envelope_id', models.CharField(blank=True, max_length=36)),
                ('evidence', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.docusignchallenge')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attempt', to='core.sandboxpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(guards, remove_guards),
    ]
