# Generated by Django 5.2.17 on 2026-10-06 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


TABLES = ['core_projectevidence', 'core_releasepackage', 'core_releaseapproval']

def guards(apps, schema_editor):
    for table in TABLES:
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(f"CREATE TRIGGER gecc_{table}_guard BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION gecc_audit_guard()")
        else:
            for action in ['UPDATE', 'DELETE']:
                schema_editor.execute(f"CREATE TRIGGER gecc_{table}_{action.lower()} BEFORE {action} ON {table} BEGIN SELECT RAISE(ABORT, 'Release evidence is immutable'); END")

def remove_guards(apps, schema_editor):
    for table in TABLES:
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(f'DROP TRIGGER gecc_{table}_guard ON {table}')
        else:
            for action in ['update', 'delete']:
                schema_editor.execute(f'DROP TRIGGER gecc_{table}_{action}')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_docusignchallenge_context_sandboxpackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=32)),
                ('data', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('msr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_evidence', to='core.msr')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleasePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_packages', to='core.signingplan')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('package_digest', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='core.releasepackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='releasepackage',
            constraint=models.UniqueConstraint(fields=('plan', 'digest'), name='release_package_unique'),
        ),
        migrations.RunPython(guards, remove_guards),
    ]
