# Generated by Django 5.2.17 on 2026-10-06 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


TABLES = ['core_sandboxobservation']

def guards(apps, schema_editor):
    for table in TABLES:
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(f"CREATE TRIGGER gecc_{table}_guard BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION gecc_audit_guard()")
        else:
            for action in ['UPDATE', 'DELETE']:
                schema_editor.execute(f"CREATE TRIGGER gecc_{table}_{action.lower()} BEFORE {action} ON {table} BEGIN SELECT RAISE(ABORT, 'Sandbox observations are immutable'); END")

def remove_guards(apps, schema_editor):
    for table in TABLES:
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(f'DROP TRIGGER gecc_{table}_guard ON {table}')
        else:
            for action in ['update', 'delete']:
                schema_editor.execute(f'DROP TRIGGER gecc_{table}_{action}')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectevidence_releasepackage_releaseapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.sandboxattempt')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.docusignchallenge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(guards, remove_guards),
    ]
