# Generated by Django 5.2.17 on 2026-10-06 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


TABLES = ['core_signingtestpackage', 'core_signingtestdecision', 'core_signingtestobservation', 'core_signingtestdocument']

def guards(apps, schema_editor):
    for table in TABLES:
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(f"CREATE TRIGGER gecc_{table}_guard BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION gecc_audit_guard()")
        else:
            for action in ['UPDATE', 'DELETE']:
                schema_editor.execute(f"CREATE TRIGGER gecc_{table}_{action.lower()} BEFORE {action} ON {table} BEGIN SELECT RAISE(ABORT, 'Signing-test records are immutable'); END")

def remove_guards(apps, schema_editor):
    for table in TABLES:
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(f'DROP TRIGGER gecc_{table}_guard ON {table}')
        else:
            for action in ['update', 'delete']:
                schema_editor.execute(f'DROP TRIGGER gecc_{table}_{action}')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sandboxobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningTestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.CharField(max_length=36)),
                ('envelope_id', models.CharField(blank=True, max_length=36)),
                ('state', models.CharField(default='AUTH_PENDING', max_length=32)),
                ('first_send_started_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.docusignchallenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigningTestObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.signingtestattempt')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.docusignchallenge')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigningTestPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_tests', to='core.releasepackage')),
            ],
        ),
        migrations.CreateModel(
            name='SigningTestDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(max_length=20)),
                ('note', models.TextField()),
                ('digest', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='core.signingtestpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signingtestattempt',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attempt', to='core.signingtestpackage'),
        ),
        migrations.CreateModel(
            name='SigningTestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=250)),
                ('content', models.BinaryField()),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retained_documents', to='core.signingtestattempt')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.signingtestobservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'document_id'), name='signing_test_document_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='signingtestpackage',
            constraint=models.UniqueConstraint(fields=('source', 'digest'), name='signing_test_package_unique'),
        ),
        migrations.RunPython(guards, remove_guards),
    ]
